urls.py
from django.urls import include,path,re_path
from django.contrib.auth.views import PasswordResetConfirmView
from rest_framework import routers
from rest_framework.authtoken import views as authviews
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

router = routers.DefaultRouter(trailing_slash = False)
router.register(r'rawtang', views.RawtangViewSet, basename="rawtang")
router.register(r'rawramp', views.RawrampViewSet, basename="rawramp")
router.register(r'rawkes', views.RawkesViewSet, basename="rawkes")

app_name = "app"
urlpatterns = [
	path("", views.index, name="index"),
	path("register/", views.user_register, name="register"),
	path("data_entry/", views.data_entry, name="data"),
	path("login/", views.user_login, name="login"),
	path("logout/", views.user_logout, name= "logout"),
	path("reset/", views.user_reset_pwd, name= "reset"),
	path("reset_confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(template_name="rafflesia/password_reset_confirm.html"), name= "reset_confirm"),
	re_path(r'^datatable/(?P<table_name>\w+)/$',views.render_table,name='table'),
	re_path(r'^serverside/(?P<table_name>\w+)/(?P<filtering>\w+)/$',views.ServersideView.as_view(),name='serverside'),
	re_path(r'^download/(?P<table_name>\w+)/$',views.download,name='download'),
	path("sedar/", views.get_sedar, name="sedar"),
	path("geotagging/", views.post_geotag, name="geotag"),
	path("api-token-auth/", authviews.obtain_auth_token, name="token"),
	path("api/", include(router.urls)),
	path("send-notification-email/",views.send_notification_email, name="send_notification_email"),
	path("handle-coordinates/",views.handle_coordinates, name="handle_coordinates"),
	path('chartraw/', views.ChartRawList.as_view(), name="chartrawlist"),
	path('chartraw/<int:pk>', views.ChartRawDetail.as_view(), name="chartrawdetail"),
]

templates/api/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <!-- jQuery -->
  <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
  <!-- Bootstrap 4 -->
  <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <!-- AdminLTE App -->
  <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
  {% block script %}{% endblock %}
  {% block styling %}{% endblock %}
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbaroptions" aria-controls="navbaroptions" aria-expanded="False" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbaroptions">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link float-left" href="{% url 'app:index' %}">Halaman Utama</a>
        </li>
      </ul>        
    {% if user.is_authenticated %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link float-right" href="{% url 'app:register' %}">Pendaftaran</a>
        </li>
        <li class="nav-item">
          <a class="nav-link float-right" href="{% url 'app:logout' %}">Log Keluar</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Selamat Datang, {{user.username}}</a>
        </li>
      </ul>
    {% else %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app:login' %}">Log Masuk</a>
        </li>
      </ul>
    {% endif %}
    </div>
  </nav>
{% block messages %}
{% endblock %}
{% block content %}
{% endblock %}
{% block footer %}
{% endblock %}
</body>
</html>

templates/api/data_entry.html
{% extends "app/admin_base.html" %}
{% block title %}Kemasukan Data{% endblock %}
{% block navbar %}
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a class="nav-link" href="{% url 'app:index' %}" >Halaman Utama</a>
      </li>
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link float-right" href="{% url 'app:table' 'sedar' %}">Data</a>
      </li>
      <li class="nav-item">
        <a class="nav-link float-right" href="{% url 'app:table' 'rawkes' %}">Data</a>
      </li>
      <li class="nav-item">
        <a class="nav-link float-right" href="{% url 'app:table' 'rawtang'%}">Data</a>
      </li>
      <li class="nav-item">
        <a class="nav-link float-right" href="{% url 'app:table' 'rawramp'%}">Data</a>
      </li>
      <li class="nav-item">
        <a class="nav-link float-right" href="{% url 'app:logout' %}">Log Keluar</a>
      </li>
    </ul>
  </nav>
{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row">
  <div class="col-lg-6">
    <br/>
    <div class="card card-primary card-outline">
      <div class="card-header">
        <h3 class="card-title">Kemasukan Data</h3>
          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="maximize"><i class="fas fa-expand"></i></button>
            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
          </div>
      </div>
      <div class="card-body">
        <div style="height: 550px;" class="overflow-auto">
          <form action="{% url 'app:data' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ rawtang_form|crispy }}
            <button class="btn btn-primary" name="tablename" value="rawtang" type="submit">Hantar</button>
          </form>
        </div>
      </div>
      <div class="card-footer">
        <a href="{% url 'app:table' 'rawtang' %}" class="card-link">Paparkan Data</a>
      </div>
    </div>
    <br/>
    <div class="card card-primary card-outline">
      <div class="card-header">
        <h3 class="card-title">Kemasukan Data</h3>
          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="maximize"><i class="fas fa-expand"></i></button>
            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
          </div>
      </div>
      <div class="card-body">
        <div style="height: 550px;" class="overflow-auto">
          <form action="{% url 'app:data' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ rawramp_form|crispy }}
            <button class="btn btn-primary" name= "tablename" value="rawramp" type="submit">Hantar</button>
          </form>
        </div>
      </div>
      <div class="card-footer">
        <a href="{% url 'app:table' 'rawramp' %}" class="card-link">Paparkan Data</a>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <br/>
    <div class="card card-primary card-outline">
      <div class="card-header">
        <h3 class="card-title">Kemasukan Data</h3>
          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="maximize"><i class="fas fa-expand"></i></button>
            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
          </div>
      </div>
      <div class="card-body">
        <div style="height: 550px;" class="overflow-auto">
          <form action="{% url 'app:data' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ rawkes_form|crispy }}
            <button class="btn btn-primary" name= "tablename" value="rawkes" type="submit">Hantar</button>
          </form>
        </div>
      </div>
      <div class="card-footer">
        <a href="{% url 'app:table' 'rawkes' %}" class="card-link">Paparkan Data</a>
      </div>
    </div>
    <br/>
  </div>
</div>
<!-- close row -->
{% endblock %}

templates/api/index.html
{% extends "app/admin_base.html" %}
{% block title %}Halaman Utama{% endblock %}
{% block navbar %}
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a class="nav-link" href="{% url 'app:data' %}" >Kemasukan Data</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a class="nav-link" href="{% url 'app:sedar' %}" >Peta Sedar</a>
      </li>
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link float-right" href="{% url 'app:register' %}">Pendaftaran</a>
      </li>
      <li class="nav-item">
        <a class="nav-link float-right" href="{% url 'app:logout' %}">Log Keluar</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Selamat Datang {{user.username}}</a>
      </li>
    </ul>
  </nav>
{% endblock %}
{% block content %}
<!-- open row -->
<br/>
<div class="row">
  <!-- open column -->
  <div class="col-lg-12">
    <div class="card card-success">
    <div class="card-header">
    <h3 class="card-title">Carta Bulanan</h3>
    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
      <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
    </div>
    </div>
    <div class="card-body">
      <div class="d-flex justify-content-center" id="bulanan-input">
      </div>
      <div class="chart" id="date-chart">
          <div class="d-flex justify-content-center">
            <div class="spinner-border text-success" role="status">
              <span class="sr-only">Loading...</span>
            </div>
          </div>
          <p class="text-center"><strong>Carta sedang dijana.</strong></p>
      </div>
    </div>
    </div>
  </div>
  <!-- close column -->
</div>
<!-- close row -->
<!-- open row -->
<br/>
<div class="row">
  <!-- open column -->
  <div class="col-lg-12">
    <div class="card card-danger">
    <div class="card-header">
    <h3 class="card-title">Carta Status</h3>
    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
      <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
    </div>
    </div>
    <div class="card-body">
      <div class="d-flex justify-content-center" id="statusks-input">
      </div>
      <div class="chart" id="statusks-chart">
          <div class="d-flex justify-content-center">
            <div class="spinner-border text-danger" role="status">
              <span class="sr-only">Pemuatan...</span>
            </div>
          </div>
          <p class="text-center"><strong>Carta sedang dijana.</strong></p>
      </div>
    </div>
    </div>
  </div>
  <!-- close column -->
</div>
<!-- close row -->
<!-- open row -->
<br/>
<div class="row">
  <!-- open column -->
  <div class="col-lg-12">
    <div class="card card-danger">
    <div class="card-header">
    <h3 class="card-title">Carta Status</h3>
    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
      <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
    </div>
    </div>
    <div class="card-body">
      <div class="d-flex justify-content-center" id="statusk-input">
      </div>
      <div class="chart" id="statuskes-chart">
        <div class="d-flex justify-content-center">
          <div class="spinner-border text-danger" role="status">
            <span class="sr-only">Pemuatan...</span>
          </div>
        </div>
        <p class="text-center"><strong>Carta sedang dijana.</strong></p>
      </div>
    </div>
    </div>
  </div>
  <!-- close column -->
</div>
<!-- close row -->
<!-- open row -->
<br/>
<div class="row">
  <!-- open column -->
  <div class="col-lg-12">
    <div class="card card-danger">
    <div class="card-header">
    <h3 class="card-title">Carta Barang</h3>
    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
      <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
    </div>
    </div>
    <div class="card-body">
      <div class="d-flex justify-content-center" id="rampasangram-input">
      </div>
      <div class="chart" id="rampasangram-chart">
        <div class="d-flex justify-content-center">
          <div class="spinner-border text-danger" role="status">
            <span class="sr-only">Pemuatan...</span>
          </div>
        </div>
        <p class="text-center"><strong>Carta sedang dijana.</strong></p>
      </div>
    </div>
    </div>
  </div>
  <!-- close column -->
</div>
<!-- close row -->
<!-- open row -->
<br/>
<div class="row">
  <!-- open column -->
  <div class="col-lg-12">
    <div class="card card-danger">
    <div class="card-header">
    <h3 class="card-title">Carta Barang</h3>
    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
      <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
    </div>
    </div>
    <div class="card-body">
      <div class="d-flex justify-content-center" id="rampasanliter-input">
      </div>
      <div class="chart" id="rampasanliter-chart">
        <div class="d-flex justify-content-center">
          <div class="spinner-border text-danger" role="status">
            <span class="sr-only">Pemuatan...</span>
          </div>
        </div>
        <p class="text-center"><strong>Carta sedang dijana.</strong></p>
      </div>
    </div>
    </div>
  </div>
  <!-- close column -->
</div>
<!-- close row -->
<!-- open row -->
<br/>
<div class="row">
  <!-- open column -->
  <div class="col-lg-12">
    <div class="card card-danger">
    <div class="card-header">
    <h3 class="card-title">Carta Barang</h3>
    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
      <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
    </div>
    </div>
    <div class="card-body">
      <div class="d-flex justify-content-center" id="rampasanpokok-input">
      </div>
      <div class="chart" id="rampasanpokok-chart">
        <div class="d-flex justify-content-center">
          <div class="spinner-border text-danger" role="status">
            <span class="sr-only">Pemuatan...</span>
          </div>
        </div>
        <p class="text-center"><strong>Carta sedang dijana.</strong></p>
      </div>
    </div>
    </div>
  </div>
  <!-- close column -->
</div>
<!-- close row -->
<!-- open row -->
<br/>
<div class="row">
  <!-- open column -->
  <div class="col-lg-12">
    <div class="card card-danger">
    <div class="card-header">
    <h3 class="card-title">Carta Barang</h3>
    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
      <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
    </div>
    </div>
    <div class="card-body">
      <div class="d-flex justify-content-center" id="rampasankeping-input">
      </div>
      <div class="chart" id="rampasankeping-chart">
        <div class="d-flex justify-content-center">
          <div class="spinner-border text-danger" role="status">
            <span class="sr-only">Pemuatan...</span>
          </div>
        </div>
        <p class="text-center"><strong>Carta sedang dijana.</strong></p>
      </div>
    </div>
    </div>
  </div>
  <!-- close column -->
</div>
<!-- close row -->
{% include "app/chartjs.html" %}
{% endblock %}

templates/api/password_reset.html
{% extends "app/base.html" %}
{% block title %}Password Reset{% endblock %}
{% block styling %}
  <style type="text/css">
  </style>
{% endblock %}
{% load crispy_forms_tags %}
{% block messages %}
<div class="d-flex align-items-center justify-content-center">
{% if messages %}
{% for message in messages %}
    <br/>
        <div class="alert {{ message.tags }}" role="alert"><strong>
        {% if "success" in message.tags %}
        Success:
        {% elif "warning" in message.tags %}
        Warning:
        {% endif %}
       {{ message }}</strong></div>
    <br/>
{% endfor %}
{% endif %}
</div>
{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>Forgot password</h1>
  <form method="POST">
    {% csrf_token %}
    {{ reset_form|crispy }}
    <button class="btn btn-primary" type="submit">Submit</button>
  </form>
</div>
{% endblock %}

templates/api/password_reset_complete.html
{% extends "app/base.html" %}
{% block title %}Password Reset Complete{% endblock %}
{% block styling %}
  <style type="text/css">
  </style>
{% endblock %}
{% block messages %}
<div class="d-flex align-items-center justify-content-center">
{% if messages %}
{% for message in messages %}
    <br/>
        <div class="alert {{ message.tags }}" role="alert"><strong>
        {% if "success" in message.tags %}
        Success:
        {% elif "warning" in message.tags %}
        Warning:
        {% endif %}
       {{ message }}</strong></div>
    <br/>
{% endfor %}
{% endif %}
</div>
{% endblock %}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'app:login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/api/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for the account with following details:

    username: {{ user }}
    email: {{ email }}
    web application: app

  Please click the link below:

    {{ protocol }}://{{ domain }}{% url 'app:reset_confirm' uid token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  Developer Team
{% endautoescape %}

templates/api/rawkes_table.html
{% extends "app/base.html" %}
{% block title %}Jadual RAWKES{% endblock %}
{% block script %}
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/scroller/2.2.0/js/dataTables.scroller.min.js"></script>
<link href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
<link href="https://cdn.datatables.net/scroller/2.2.0/css/scroller.dataTables.min.css" rel="stylesheet" type="text/css" />
<script src="https://cdn.datatables.net/buttons/2.1.0/js/dataTables.buttons.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/2.1.0/js/buttons.html5.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/2.1.0/js/buttons.print.min.js" type="text/javascript"></script>
<link href="https://cdn.datatables.net/buttons/2.1.0/css/buttons.dataTables.min.css" rel="stylesheet" type="text/css" />
<script src="https://rawgit.com/moment/moment/2.2.1/min/moment.min.js"></script>
{% endblock %}
{% block styling %}
<style type="text/css">
pre {
  width: 900px;
  border: 0;
  background-color: transparent;
  font-family: Arial, Helvetica, sans-serif;
  font-size: 10pt;
}
</style>
{% endblock %}
{% block messages %}
<div class="d-flex align-items-center justify-content-center">
{% if messages %}
{% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert"><strong>{{ message }}</strong></div>
{% endfor %}
{% endif %}
</div>
{% endblock %}
{% block content %}
{% load static %}
{% load app_extras %}
<pre>Untuk menyimpan data tersebut, dua pilihan telah disediakan:<br/>
1. Hanya memuat turun rekod yang dipaparkan sebagai fail CSV<br/>
2. Memuat turun kesemua rekod sebagai fail CSV<br/>
</pre>
{% if request.user|has_group:"MFRLab" %}
<table id='rawkes_table' class='display text-center'>
  <thead>
    <tr>
    </tr>
  </thead>
  <tbody>
  </tbody>
  <tfoot>
    <tr>
    </tr>
  </tfoot>
</table>
<script type="text/javascript">
$(document).ready(() => {
    $('#rawkes_table thead th').each( function () {
        let title = $('#rawkes_table tfoot th').eq($(this).index()).text();
        $(this).html('<div class="display text-center";><input type="text"; class="display text-center"; placeholder="Cari '+title+' ";></div>');
    });
    let table = $('#rawkes_table').DataTable({
    serverSide: true,
    sAjaxSource: "{% url 'app:serverside' 'rawkes' 'off' %}",
    columns: [
        { data: 0, render:
          function ( data, type, row ) {
            let pk = row[0];
            data = "<a href='{% url 'app:table' 'rawkes' %}?action=del&pk="+pk+"'>"+pk+"</a>";
            return data;
          }        
        },
        { data: 1 },
        { data: 2 },
        { data: 3 },
        { data: 4 },
        { data: 5 },
        { data: 6 , render:
          function ( data, type, row ) {
            let timestamp = row[6];
            if (timestamp != null) { //to deal with null date for rawtang LLPK record
              data = moment(timestamp,'YYYY-MM-DD').format('YYYY-MM-DD');
            } else {
              data = timestamp;
            }
            return data;
          }
        },
        { data: 7 },
        { data: 8 },
        { data: 9 },
        { data: 10 },
        { data: 11 },
        { data: 12 },
        { data: 13 },
        { data: 14 },
        { data: 15 },
        { data: 16 },
        { data: 17 },
        { data: 18 },
        { data: 19 }
    ],
    scrollY: 350,
    scrollX: true,
    scroller: true,
    scrollCollapse: true,
    deferRender: true,
    dom: 'Bfrtip',
    buttons: [
        {
            extend: 'csv',
            text: 'CSV - HANYA REKOD YANG DIPAPARKAN',
            exportOptions: {
                columns: [ 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19 ],
                orthogonal: 'export',
                stripHtml: true
            }
        },
        {
            text: 'CSV - KESEMUA REKOD',
            action: function ( e, dt, node, config ) {
                window.location = "{% url 'app:download' 'rawkes'%}";
            }
        }
    ]
    });
    table.columns().eq(0).each(function(idx) {
        $('input',table.column(idx).header()).on('input',function() {
            table.column(idx).search(this.value).draw();
        });
    });
});
</script>
{% else %}
<table id='rawkes_table' class='display text-center'>
  <thead>
    <tr> 
    </tr>
  </thead>
  <tbody>
  </tbody>
  <tfoot>
    <tr> 
    </tr>
  </tfoot>
</table>
<script type="text/javascript">
$(document).ready(() => {
    $('#rawkes_table thead th').each( function () {
        let title = $('#rawkes_table tfoot th').eq($(this).index()).text();
        $(this).html('<div class="display text-center";><input type="text"; class="display text-center"; placeholder="Cari '+title+' ";></div>');
    });
    let table = $('#rawkes_table').DataTable({
    serverSide: true,
    sAjaxSource: "{% url 'app:serverside' 'rawkes' 'on' %}",
    columns: [
        { data: 0 },
        { data: 1 },
        { data: 2 },
        { data: 3 },
        { data: 4 },
        { data: 5, render:
          function ( data, type, row ) {
            let timestamp = row[5];
            if (timestamp != null) { //to deal with null date for rawtang LLPK record
              data = moment(timestamp,'YYYY-MM-DD').format('YYYY-MM-DD');
            } else {
              data = timestamp;
            }
            return data;
          }
        },
        { data: 6 },
        { data: 7 },
        { data: 8 },
        { data: 9 },
        { data: 10 },
        { data: 11 },
        { data: 12 },
        { data: 13 },
        { data: 14 },
        { data: 15 },
        { data: 16 },
        { data: 17 }
    ],
    scrollY: 350,
    scrollX: true,
    scroller: true,
    scrollCollapse: true,
    deferRender: true,
    dom: 'Bfrtip',
    buttons: [
        {
            extend: 'csv',
            text: 'CSV - HANYA REKOD YANG DIPAPARKAN',
            exportOptions: {
                columns: [ 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18 ],
                orthogonal: 'export',
                stripHtml: true
            }
        },
        {
            text: 'CSV - KESEMUA REKOD',
            action: function ( e, dt, node, config ) {
                window.location = "{% url 'app:download' 'rawkes'%}";
            }
        }
    ]
    });
    table.columns().eq(0).each(function(idx) {
        $('input',table.column(idx).header()).on('input',function() {
            table.column(idx).search(this.value).draw();
        });
    });
});
</script>
{% endif %}
{% endblock %}

templates/api/register.html
{% extends "app/base.html" %}
{% block title %}Register{% endblock %}
{% block styling %}
  <style type="text/css">
  </style>
{% endblock %}
{% load crispy_forms_tags %}
{% block messages %}
<div class="d-flex align-items-center justify-content-center">
{% if messages %}
{% for message in messages %}
    <br/>
        <div class="alert {{ message.tags }}" role="alert"><strong>
        {% if "success" in message.tags %}
        Success:
        {% elif "warning" in message.tags %}
        Warning:
        {% endif %}
       {{ message }}</strong></div>
    <br/>
{% endfor %}
{% endif %}
</div>
{% endblock %}
{% block content %}         
  <div class="container py-5">
  	<h1>Register</h1>
  	<form method="POST">
  		{% csrf_token %}
  		{{ register_form|crispy }}                    
  		<button class="btn btn-primary" type="submit">Register</button>
  	</form>
  	<p class="text-center">Already have an account? Please <a href="{% url 'app:login' %}">login</a>.</p>
  </div>
{% endblock %}